# **NumPy入門**



まず使うためには以下のようなコマンドを打ち込みます：

In [1]:
import numpy as np

このようにしておくと、np.commandでnumpyのコマンドを使えるようになります。numpyは配列を取り扱うライブラリーです。そこでまずはnumpy配列とは何かを説明します。

pythonにはリスト型がありましたが、「リストのリスト」を考えることもできます。

In [32]:
T = [[3, 1], [5, 2]]

このリストを以下のように書くと、行列に見える気がします。

```python
T = [[3,1],
     [5,2]]
```

リストでは T[n] でn番目の要素にアクセスできるのでした。

In [33]:
x = T[0]
x

[3, 1]

今、Tはリストのリストだったので、その要素xは再びリストです。このリストxの要素にアクセスするにはx[m]で良いはずです。

In [34]:
x[1]

1

実は、xを経由しなくても直接 T[n][m]と書いても同じ結果が得られます。

In [31]:
T[0][1]

1

添え字二つで数を指定することは、行列を定義しているのと同じです。リストの入れ子構造はもっと一般化できて、一般には以下のような添え字付けが可能です：

```python
T[k][l][m][n]...
```

numpyを用いると、このような型の値に関する計算を高速に行ってくれます。

## **numpy配列の作り方**

numpyの配列に関する処理を使うためには、配列をpythonのリストではなく、np.arrayのオブジェクトとして再定義する必要があります。

> ### [**pythonリストとnumpy配列**](https://numpy.org/doc/stable/user/absolute_beginners.html#whats-the-difference-between-a-python-list-and-a-numpy-array)
>
>> <font color=dodgerblue> **np.array $\leftarrow$ リスト**</font>
>>```python
>> x_np = np.array(x_list)
>> ```
>
>> <font color=dodgerblue> **リスト $\leftarrow$ np.array**</font>
>>```python
>>x_list = x_np.tolist()
>> ```

In [13]:
x_np = np.array([[2, 1], [5, 3]])
x_np

array([[2, 1],
       [5, 3]])

In [14]:
x_list = x_np.tolist()
x_list

[[2, 1], [5, 3]]

よく使う配列は、numpy側で生成コマンドが用意されています：

> ### [**便利な配列生成コマンド**](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array)
>
>> <font color=dodgerblue>**[0,0,...,0]や[1,1,...,1]のnp.array**</font>
>>```python
>>np.zeros(N)
>>np.ones(N)
>> ```
>> <font color=gray> np.empty(N)というのでも0埋めできるようです。</font>
>    
>> <font color=dodgerblue>**[0,1,2,...N-1]のnp.array**</font>
>>```python
>> np.arange(N)
>> ```
> <font color=gray> "range"ではなく"arange"です。</font>
>
>> <font color=dodgerblue>**xからyまでをN等分したnp.array**</font>
>> ```python
>>np.linspace(x, y, N)
>> ```


In [22]:
np.zeros(10), np.ones(10)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(-1, 1, 10) # default N=50

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

（擬似）乱数も生成できます。乱数生成に関してはnumpyのバージョン1.17.0以降で[仕様変更](https://numpy.org/doc/stable/reference/random/new-or-different.html#new-or-different)があったので注意が必要です。おそらく、しばらくは仕様変更後のコードと変更前のコードが混在すると思うので、どちらも紹介します。

> ### [**乱数による配列生成(numpy.version≧1.17.0)**](https://numpy.org/doc/stable/reference/random/index.html#numpyrandom)
>
> <font color=dodgerblue>**擬似乱数生成器とシードの固定**</font>
> ```python
> rng = np.random.default_rng(seed: int)
> ```
> <font color=gray> default_rngはデフォルトの乱数生成器([PCG-64](https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html#numpy.random.PCG64))で、引数に整数であるseedを入力して使います。例えば以下のようにしてランダムな配列を作ることができます。
>> <font color=dodgerblue>**N個のランダム数からなる配列生成**</font>
>> ```python
>> rng.uniform(xmin, xmax, N) # uniformly distributed in [xmin, xmax]
>> rng.normal(mean, std, N) # gaussian with mean and standard deviation=std
>> ```




In [41]:
rng = np.random.default_rng(123)
rng.uniform(0, 1, 10)

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

古い方のランダム配列もまだ使えます。

> ### [**乱数による配列生成(Legacy)**](https://docs.scipy.org/doc/numpy-1.16.1/reference/routines.random.html)
>
> <font color=dodgerblue>**擬似乱数状態とシードの固定**</font>
> ```python
> np.random.seed(seed: int)
> ```
> <font color=gray> seedの設定はなくても良いです。例えば以下のようにしてランダムな配列を作ることができます。生成器は[MT19937](https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.random.get_state.html?highlight=mt19937)しか使えないと思われます。
>> <font color=dodgerblue>**N個のランダム数からなる配列生成**</font>
>> ```python
>> np.random.uniform(xmin, xmax, N) # uniformly distributed in [xmin, xmax]
>> np.random.normal(mean, std, N) # gaussian with mean and standard deviation=std
>> ```


In [42]:
np.random.seed(123) # not necessary
np.random.uniform(0, 1, 10)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

## **numpy配列の機能**

np.arrayには様々な便利機能があります。

>### [**要素にアクセスする方法**](https://numpy.org/doc/stable/user/basics.indexing.html)
>
> x_npをshapeが(M, N, ...)であるようなnumpy配列とします
>> <font color=dodgerblue>**特定の要素にアクセス**</font>
>> ```python
>> x_np[m, n, ...]
>> ```
>
>> <font color=dodgerblue>**まとめた要素にアクセス**</font>
>> ```python
>> x_np[m, n0:n1, ...]
>> ```
>> <font color=gray>n0からn1-1までの要素にアクセス。特に:だけだと、全要素にアクセスとなります。</font>



In [15]:
x_np = np.array([[1,2,3], [4,5,6]])
x_np

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x_np[0,0]

1

In [18]:
x_np[0,0:2]

array([1, 2])

>### [**データの型**](https://numpy.org/doc/stable/reference/arrays.dtypes.html?highlight=float32)
>
>arrayの要素を構成する数の型を**dtype**と呼びます。様々なarrayのdtypeを書くと以下のようになります。
>
>|array(x_np)|dtype(x_np.dtype)|
>|:---|:---|
>|`[1 2 3]`|`np.int`
>|`[1.0 2.0 3.0]`|`np.float`
>|`[1.0+0.0j 2.0+0.0j 3.0+0.0j]`|`np.complex`
>
>x_npをarrayとしたとき、そのdtypeはx_np.dtypeで手に入れることができます：
>
>> <font color=dodgerblue>**要素の型を表す変数：.dtype**</font>
>>
>> 既存のarrayをx_np だとします。
>>```python
>>x_np.dtype # -> dtype(type)
>> ```
>    
>> <font color=dodgerblue>**型を変更したarrayを返す関数：.astype()**</font>
>>
>> 既存のarrayをx_np だとします。
>>```python
>>x_np = x_np.astype(dtype)
>> ```
>> <font color=gray> dtypeには例えば以下があります：
>> - np.intX：Xビット整数、X=8, 16, 32, 64
>> - np.floatX：Xビット実数、X = 16, 32, 64, 128
>> - np.complexX：Xビット複素数、X = 64, 128, 256

In [85]:
x_np = np.array([1,2])
x_np.dtype

dtype('int64')

In [96]:
x_np = np.array([1, 2])
x_np = x_np.astype(np.float32)
x_np

array([1., 2.], dtype=float32)

ちなみにarrayを作成するときに、引数dtypeで型を指定できますが、同じことを.astype()でもできるので、後者を覚えておくのが良いかと思います：

In [98]:
x_np1 = np.array(1, dtype=np.float32)
x_np2 = np.array(1).astype(np.float32)

x_np1 == x_np2

True

>### [**データの形状**](https://numpy.org/doc/1.19/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)
>
>同じ値の要素も、色々な形状を持つことができます。numpyではこれを**shape**と呼びます。例えば 1,2,3,4,5,6 の組み合わせで様々なarrayとそのshapeを列挙すると以下のようになります。
>
>|array(x_np)|shape(x_np.shape)|
>|:---|:---|
>|`[1 2 3 4 5 6]`|`(6,)`
>|`[[1] [2] [3] [4] [5] [6]]`|`(6, 1)`
>|`[[1 2] [3 4] [5 6]]`|`(3, 2)`
>|...|...
>
>x_npをarrayとしたとき、そのshapeはx_np.shapeで手に入れることができます：
>
>> <font color=dodgerblue>**形状の変数：.shape**</font>
>>```python
>>x_np.shape # -> (dimension0, dimension1, ...)
>> ```
>> <font color=gray> 出力はtupleです。</font>
>
>shapeを変更することも可能で、よく使います：
>    
>> <font color=dodgerblue>**形状変更したarrayを返す関数：.reshape()**</font>
>>```python
>>x_np = x_np.reshape(m, n, ...)
>> ```
>> <font color=gray> 新しいshapeに当てはめ直すルールは、</font>
>>
>> <font color=gray>1. 一旦、shapeの最後の軸から順に1列に並べる</font>
>> ```python
>>#example
>>[[a b c] [d e f]] -> [a b c d e f]
>> ```
>> <font color=gray>2. 変換後に指定したshapeの最後の軸からまた順に並べなおす</font>
>> ```python
>>#example
>>[a b c d e f] ->  [[a b] [c d] [e f]]
>> ```
>>
>> となっているようです。


In [35]:
x_np = np.array([[1,2],
                              [3,4]])
x_np.shape

(2, 2)

In [40]:
x_np = np.arange(6)
x_np = x_np.reshape(2, 3)
x_np

array([[0, 1, 2],
       [3, 4, 5]])

## **numpy配列の計算**

numpy配列の四則演算は、成分ごとに行われます：

In [29]:
x_np = np.arange(6).reshape(2, 3)
y_np = np.array([[1, 1, 1],
                  [10, 10, 10]])

print("x_np =\n", x_np)
print("y_np =\n", y_np)
print("x_np*y_np =\n", x_np*y_np)

x_np =
 [[0 1 2]
 [3 4 5]]
y_np =
 [[ 1  1  1]
 [10 10 10]]
x_np*y_np =
 [[ 0  1  2]
 [30 40 50]]


様々な関数が使えます。

> ### [**数学の関数**](https://numpy.org/doc/stable/reference/routines.math.html)
>> <font color=dodgerblue>**初等関数**</font>
>> ```python
>> f(x_np)
>> ```
>> - 三角関数：f=np.sin, np.cos, np.tan, ...
>> - 双曲関数：f=np.sinh, np.cosh, np.tanh, ...
>> - 指数、対数関数：f=np.exp, np.log, ...
>
>> <font color=dodgerblue>**軸にわたる操作**</font>
>> ```python
>> f(x_np, axis: int, keepdims: bool)
>> ```
>>
>> <font color=gray>axisはintか、intからなるtupleで指定し、どの軸方向に和を取るかを指定します。計算の結果、配列の次元が低くなりますが、keepdims=Trueとすると、その部分はshape1として埋めてくれます。</font>
>> - f=np.sum：和
>> - f=np.prod：積
>> - f=np.max：最大値
>> - f=np.min：最小値
>>
>> <font color=gray> 機械学習で特によく使うのが、統計処理です：</font>
>> - f=np.mean：平均値
>> - f=np.std：標準偏差


In [44]:
x_np = np.linspace(0, 2*np.pi) # np.pi = π
np.sin(x_np)

array([ 0.00000000e+00,  1.27877162e-01,  2.53654584e-01,  3.75267005e-01,
        4.90717552e-01,  5.98110530e-01,  6.95682551e-01,  7.81831482e-01,
        8.55142763e-01,  9.14412623e-01,  9.58667853e-01,  9.87181783e-01,
        9.99486216e-01,  9.95379113e-01,  9.74927912e-01,  9.38468422e-01,
        8.86599306e-01,  8.20172255e-01,  7.40277997e-01,  6.48228395e-01,
        5.45534901e-01,  4.33883739e-01,  3.15108218e-01,  1.91158629e-01,
        6.40702200e-02, -6.40702200e-02, -1.91158629e-01, -3.15108218e-01,
       -4.33883739e-01, -5.45534901e-01, -6.48228395e-01, -7.40277997e-01,
       -8.20172255e-01, -8.86599306e-01, -9.38468422e-01, -9.74927912e-01,
       -9.95379113e-01, -9.99486216e-01, -9.87181783e-01, -9.58667853e-01,
       -9.14412623e-01, -8.55142763e-01, -7.81831482e-01, -6.95682551e-01,
       -5.98110530e-01, -4.90717552e-01, -3.75267005e-01, -2.53654584e-01,
       -1.27877162e-01, -2.44929360e-16])

In [58]:
x_np = np.arange(12).reshape(3, 4)
f = np.sum
print(x_np)
print(f(x_np, axis=0, keepdims=True))
print(f(x_np, axis=1, keepdims=True))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 15 18 21]]
[[ 6]
 [22]
 [38]]


> ### [**軸の入れ替え**](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html#numpy.transpose)
> ```python
> np.transpose(x_np, axes: tuple)
> ```
> <font color=gray> 行列の転置に対応する操作。axesには、どのような順に入れ替えたいかを、元のarrayの軸の番号で書きます。</font>

In [63]:
x_np = np.arange(24).reshape(2,3,4)
x_np

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [65]:
np.transpose(x_np, axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

> ### [**ブロードキャスティング**](https://numpy.org/doc/1.19/user/theory.broadcasting.html#array-broadcasting-in-numpy)
> 配列どうしの計算は、形を整えなくても、ある程度自動化されます。詳しくはリンク先を見てください。

In [59]:
x_np = np.arange(12).reshape(3, 4)
x_np + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])